# Generated by Django 5.0 on 2023-12-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app_ModelForm', '0002_samplemodel02'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel03',
            fields=[
                ('big_auto_field', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
